export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-black text-gray-300 p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-purple-400 mb-8">Terms and Conditions</h1>
        
        <p className="text-sm text-gray-500 mb-8">Last Updated: November 24, 2025</p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">1. Acceptance of Terms</h2>
          <p className="mb-4">
            By accessing and using the Lilith Echo Alexa Skill ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">2. Service Description</h2>
          <p className="mb-4">
            Lilith Echo is an AI-powered conversational Alexa skill that provides interactive, personalized conversations with a character named Lilith. The Service uses artificial intelligence to generate responses and remembers conversation context to create a continuous experience.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">3. Age Restriction</h2>
          <p className="mb-4">
            The Service is intended for users aged 18 and above. The Service contains mature themes, dark humor, and intense personality interactions that may not be suitable for minors. By using the Service, you confirm that you are at least 18 years old.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">4. User Conduct</h2>
          <p className="mb-4">You agree to use the Service only for lawful purposes. You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Use the Service in any way that violates any applicable federal, state, local, or international law</li>
            <li>Attempt to gain unauthorized access to the Service or its related systems</li>
            <li>Use the Service to transmit any harmful code, viruses, or malicious software</li>
            <li>Attempt to reverse engineer or extract the underlying AI models or algorithms</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">5. AI-Generated Content</h2>
          <p className="mb-4">
            All responses from Lilith are generated by artificial intelligence. The Service does not provide professional advice (medical, legal, financial, or therapeutic). The content is for entertainment purposes only. We are not responsible for any decisions made based on AI-generated responses.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">6. Conversation Storage</h2>
          <p className="mb-4">
            The Service stores your conversations to provide personalized, context-aware responses. By using the Service, you consent to the storage and processing of your conversation data as described in our Privacy Policy.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">7. Disclaimer of Warranties</h2>
          <p className="mb-4">
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. We do not warrant that the Service will be uninterrupted, secure, or error-free. We do not warrant the accuracy, completeness, or reliability of any AI-generated content.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">8. Limitation of Liability</h2>
          <p className="mb-4">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">9. Content and Themes</h2>
          <p className="mb-4">
            The Service features a character with dark, gothic, and romantic themes. Content may include:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Dark humor and sarcastic commentary</li>
            <li>Gothic and supernatural themes</li>
            <li>Romantic and intimate language</li>
            <li>Suspenseful and mysterious narratives</li>
          </ul>
          <p className="mt-4">
            All content is fictional and generated by AI for entertainment purposes.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">10. Service Modifications</h2>
          <p className="mb-4">
            We reserve the right to modify, suspend, or discontinue the Service at any time without notice. We may also update these Terms and Conditions periodically. Your continued use of the Service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">11. Third-Party Services</h2>
          <p className="mb-4">
            The Service uses third-party services including:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>Amazon Alexa Voice Service</li>
            <li>Google Gemini AI for conversation generation</li>
            <li>MongoDB for data storage</li>
          </ul>
          <p className="mt-4">
            These services have their own terms of service and privacy policies.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">12. Data Deletion</h2>
          <p className="mb-4">
            You may request deletion of your conversation data at any time by contacting us. Upon request, we will delete all stored conversations and user data within 30 days.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">13. Governing Law</h2>
          <p className="mb-4">
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which the service provider operates, without regard to its conflict of law provisions.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">14. Contact Information</h2>
          <p className="mb-4">
            For questions about these Terms and Conditions, please contact us at:
          </p>
          <p className="ml-4">Email: nandakishorep212@gmail.com</p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-purple-300 mb-4">15. Severability</h2>
          <p className="mb-4">
            If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect.
          </p>
        </section>

        <div className="mt-12 pt-8 border-t border-gray-700 text-center text-sm text-gray-500">
          <p>© 2025 Lilith Echo. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
